### PR TITLE
Fast python unpackers

### PR DESCRIPTION
**Pull request by jmcarcell**
After some discussion related to https://github.com/DUNE-DAQ/detdataformats/pull/8, it was decided it was better to have all the python unpackers in the same place. This PR adds the same, unpackers for wib, wib2 and daphne frames and a test file to check the speed and correctness of the unpackers.
The names are `np_array_adc` and `np_array_timestamp` for the unpackers for the whole fragment and there is a version that acceps a pointer to data with the same name plus a `_data`. My proposed interface to call them works like this:
```
from rawdatautils.unpack.wib import np_array_adc, np_array_timestamp
```
so one only has to change `wib` to `wib2` or to `daphne` to get the different decoders. They all have the same but I don't expect to be a conflict within the same script. I also didn't like to make a `wib`, `wib2` and a `daphne` submodules of `rawdatautils` since we may have some utilities that work for more than one format.
I preserved the history of the PR in `detdataformats`

### CODE REVIEW

**Comment by alessandrothea** [comment]
Sorry for the long silence. The code looks good.
I've noticed that some files in `pybindsrc` have `.cc` extension, which means they're not picked up by cmake.
Is that intentional?

**Comment by jmcarcell** [comment]
No worries, yes it is intentional since they are included in the main `unpack.cpp` they are compiled there. If they have a `.cpp` they will be compiled twice and it won't work because of redefinitions. Alternatively I could add include guards and have them have a `.cpp` extension, but I think it's fine since the actual code should only be needed in one file (the file that defines the bindings)

**Comment by alessandrothea** [comment]
Right, but it's not fine. We have well-established naming conventions for files and extensions that have to be applied consistently to every repository.
There are only 2 options here: 1) using `extern` declarations (see `detdataformats`) or 2) adding private header files in `pythonsrc`.

**Comment by jmcarcell** [comment]
Done, they are all now `.cpp`. I added `extern` declarations instead of several header files. If the number of functions grows a lot then I'd prefer header files but for now I think it's fine

**Pull request merged**
